#!/bin/sh

export basedir=$PWD

# compile lda code
cd lib/lda-c-dist; make || exit

# compile using ant
cd $basedir; ant -f build.xml || exit

# data = {'med.out.1', 'test.5000.data'}
#data="test.5000.data"
#data="knnc_toy.data";
#data="med.out.1"
data="alldata_bf_sample20000b.out"
#data="alldata_sample0.1.out"
userdata=$data.`whoami`

echo $userdata

# download test.data if it doesn't exist

if test ! -f /tmp/$data.`whoami`; then
   cd /tmp/
   wget http://eecs.berkeley.edu/~darrenk/$data --output-document=$userdata
   cd $basedir
fi


out_dir=experiment-$(date -u +%F.%T%Z)
mkdir $out_dir || exit
echo Output will go in $out_dir

#0.1,0.3,0.5,0.7,0.9 \
args=\
"-Dplusone.testWordPercents=0.5 \
 -Dplusone.kValues=1,5,10,15,20 \
 -Dplusone.closestKValues=5,20,50,75,100,150,200 \
 -Dplusone.enableTest.lda=false \
 -Dplusone.enableTest.knnc=true \
 -Dplusone.enableTest.knn=true \
 -Dplusone.enableTest.knnrw=false \
 -Dplusone.enableTest.dtrw=false \
 -Dplusone.enableTest.baseline=true \
 -Dplusone.enableTest.lsi=true \
 -Dplusone.outPath=$out_dir"

# options to sample cpu
# -agentlib:hprof=cpu=samples
# -agentlib:hprof=heap=sites

# options for memory
# -Xmx4096m

java -Xmx4096m -cp Plusone.jar:lib/jars/ejml-0.17.jar $args plusone.Main /tmp/$userdata 0.8 0.3
